WITH RECURSIVE LINEAGE AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GEN
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL

    UNION ALL

SELECT 
    C.ID,
    C.PARENT_ID, 
    P.GEN+1 AS GEN
FROM ECOLI_DATA C
JOIN LINEAGE P ON C.PARENT_ID = P.ID
)

SELECT ID 
FROM LINEAGE
WHERE GEN = 3
ORDER BY ID;