-- 자식이 없는 아이템 찾기
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT A.ITEM_ID 
    FROM ITEM_INFO A
    JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
    GROUP BY A.ITEM_ID
)
ORDER BY ITEM_ID DESC;