WITH RECURSIVE lineage AS (
  SELECT ID, PARENT_ID, 1 AS gen
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  SELECT c.ID, c.PARENT_ID, p.gen + 1
  FROM ECOLI_DATA c
  JOIN lineage p ON c.PARENT_ID = p.ID
)
SELECT
  COUNT(*) AS COUNT,
  l.gen  AS GENERATION
FROM lineage l
WHERE NOT EXISTS (   
  -- 행이 존재하는지 확인
  SELECT 1 
  FROM ECOLI_DATA x
  WHERE x.PARENT_ID = l.ID
)
GROUP BY l.gen
ORDER BY GENERATION;
