WITH TOTAL_AMOUNT AS (
    SELECT B.FLAVOR, SUM(IFNULL(A.TOTAL_ORDER,0) + B.TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF A
    RIGHT JOIN JULY B ON A.SHIPMENT_ID = B.SHIPMENT_ID
    GROUP BY B.FLAVOR
    ORDER BY TOTAL DESC
    LIMIT 3
)

SELECT FLAVOR
FROM TOTAL_AMOUNT;

