-- 안료된 중고거래의 총금액이 70만원 이상
SELECT 
    U.USER_ID,
    U.NICKNAME,
    SUM(N.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD N
JOIN USED_GOODS_USER U ON N.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;
