-- 1단계: 8~10월 동안 총 5회 이상 대여된 자동차 ID 찾기
WITH CAR_FILTER AS (
    SELECT 
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
      AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

-- 2단계: 그 자동차들에 대한 월별 대여 횟수 집계
SELECT
    MONTH(H.START_DATE) AS MONTH,
    H.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_FILTER F
  ON H.CAR_ID = F.CAR_ID
WHERE H.START_DATE >= '2022-08-01'
  AND H.START_DATE < '2022-11-01'
GROUP BY MONTH(H.START_DATE), H.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;